version: "3"

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    env_file:
      - .env
    restart: always
    expose:
      - ${MOSQUITTO_PORT}
    networks:
      - iot
    volumes:
      - mosquitto-all:/mosquitto
      - ${MOSQUITTO_CFG_PATH}:/mosquitto/config/mosquitto.conf
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.mqtt.rule=HostSNI(`mqtt.${DOMAIN_NAME}`)"
      - "traefik.tcp.routers.mqtt.entrypoints=mqtt"
      - "traefik.tcp.routers.mqtt.tls.certresolver=myresolver"
      - "traefik.tcp.services.mqtt.loadbalancer.server.port=${MOSQUITTO_PORT}"

  influxdb:
    image: influxdb:latest
    volumes:
      - influxdb-storage:/var/lib/influxdb2:rw
      - influxdb-config:/etc/influxdb2
    env_file:
      - .env
    entrypoint: ["./entrypoint.sh"]
    restart: always
    expose:
      - ${DOCKER_INFLUXDB_INIT_PORT}
    networks:
      - iot
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.influxdb-http.rule=Host(`influxdb.${DOMAIN_NAME}`)"
      - "traefik.http.routers.influxdb-http.entrypoints=web"
      - "traefik.http.routers.influxdb-http.middlewares=influxdb-https"
      - "traefik.http.middlewares.influxdb-https.redirectscheme.scheme=https"
      - "traefik.http.routers.influxdb.rule=Host(`influxdb.${DOMAIN_NAME}`)"
      - "traefik.http.routers.influxdb.entrypoints=websecure"
      - "traefik.http.routers.influxdb.tls.certresolver=myresolver"
      - "traefik.http.services.influxdb.loadbalancer.server.port=${DOCKER_INFLUXDB_INIT_PORT}"

  telegraf:
    image: telegraf:latest
    volumes:
      - ${TELEGRAF_CFG_PATH}:/etc/telegraf/telegraf.conf:rw
    env_file:
      - .env
    depends_on:
      - influxdb
      - mosquitto
    restart: always
    networks:
      - iot

  grafana:
    image: grafana/grafana-oss:latest
    volumes:
      - ${GRAFANA_PROVISIONING_PATH}:/etc/grafana/provisioning
      - grafana-storage:/var/lib/grafana:rw
    env_file:
      - .env
    depends_on:
      - influxdb
    expose:
      - ${GRAFANA_PORT}
    networks:
      - iot
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana-http.rule=Host(`grafana.${DOMAIN_NAME}`)"
      - "traefik.http.routers.grafana-http.entrypoints=web"
      - "traefik.http.routers.grafana-http.middlewares=grafana-https"
      - "traefik.http.middlewares.grafana-https.redirectscheme.scheme=https"
      - "traefik.http.routers.grafana.rule=Host(`grafana.${DOMAIN_NAME}`)"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.tls.certresolver=myresolver"
      - "traefik.http.services.grafana.loadbalancer.server.port=${GRAFANA_PORT}"

  traefik:
    image: traefik:latest
    command:
      #- "--log.level=DEBUG"
      #- "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.mqtt.address=:1883"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=drumm@fh-aachen.de"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    labels:
      #- "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.${DOMAIN_NAME}`)"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.tls.certresolver=myresolver"
      - "traefik.http.routers.dashboard.service=api@internal"
    depends_on:
      - influxdb
      - grafana
      - mosquitto
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "1883:1883"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik/letsencrypt:/letsencrypt"
    networks:
      - iot

networks:
  iot:

volumes:
  mosquitto-all:
  grafana-storage:
  influxdb-storage:
  influxdb-config:
