version: "3"

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    env_file:
      - .env
    restart: always
    ports:
      - ${MOSQUITTO_PORT}:1883
    networks:
      - iot
    volumes:
      - mosquitto-all:/mosquitto
      - ${MOSQUITTO_CFG_PATH}:/mosquitto/config/mosquitto.conf

  influxdb:
    image: influxdb:latest
    volumes:
      - influxdb-storage:/var/lib/influxdb2:rw
      - influxdb-config:/etc/influxdb2
    env_file:
      - .env
    entrypoint: ["./entrypoint.sh"]
    restart: always
    ports:
      - ${DOCKER_INFLUXDB_INIT_PORT}:8086
    networks:
      - iot

  telegraf:
    image: telegraf:latest
    volumes:
      - ${TELEGRAF_CFG_PATH}:/etc/telegraf/telegraf.conf:rw
    env_file:
      - .env
    depends_on:
      - influxdb
      - mosquitto
    restart: always
    networks:
      - iot

  grafana:
    image: grafana/grafana-oss:latest
    volumes: 
      - ${GRAFANA_PROVISIONING_PATH}:/etc/grafana/provisioning
      - grafana-storage:/var/lib/grafana:rw
    env_file:
      - .env
    depends_on:
      - influxdb
    ports:
      - ${GRAFANA_PORT}:3000
    networks:
      - iot

networks:
  iot:

volumes:
  mosquitto-all:
  grafana-storage:
  influxdb-storage:
  influxdb-config:
